export const CREATE_PROJECT = "CREATE_PROJECT";
export const REMOVE_PROJECT = "REMOVE_PROJECT";
export const OPEN_PROJECT = "OPEN_PROJECT";
export const CLOSE_PROJECT = "CLOSE_PROJECT";

export const CREATE_VACANCY = "CREATE_VACANCY";
export const REMOVE_VACANCY = "REMOVE_VACANCY";
export const OPEN_VACANCY = "OPEN_VACANCY";
export const CLOSE_VACANCY = "CLOSE_VACANCY";

export const ONLY_OPENED_TOGGLE = "ONLY_OPENED_TOGGLE";
export const UPDATE_SEARCH_QUERY = "UPDATE_SEARCH_QUERY";
